version: "3.2"
services:
  aptabase_db:
    container_name: aptabase_db
    image: postgres:15-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: ${APTABASE_POSTGRES_PASSWORD}

  aptabase_events_db:
    container_name: aptabase_events_db
    image: clickhouse/clickhouse-server:23.8.4.69-alpine
    restart: always
    volumes:
      - events-db-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: ${APTABASE_POSTGRES_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  aptabase:
    container_name: aptabase_app
    image: ghcr.io/aptabase/aptabase:main
    restart: always
    depends_on:
      - aptabase_events_db
      - aptabase_db
    ports:
      - 8000:80
    environment:
      BASE_URL: ${APTABASE_BASE_URL} # replace with your ip or domain, including port if needed
      AUTH_SECRET: ${APTABASE_AUTH_SECRET} # get a strong secret from https://randomkeygen.com/
      DATABASE_URL: Server=aptabase_db;Port=5432;User Id=aptabase;Password=${APTABASE_POSTGRES_PASSWORD};Database=aptabase
      CLICKHOUSE_URL: Host=aptabase_events_db;Port=8123;Username=aptabase;Password=${APTABASE_POSTGRES_PASSWORD}

volumes:
  db-data:
    driver: local
  events-db-data:
    driver: local
